In [1]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
HF_TOKEN = userdata.get('HF_TOKEN')

from huggingface_hub import login
if HF_TOKEN:
    login(token=HF_TOKEN)

In [2]:
import os
!git clone https://oauth2:{GITHUB_TOKEN}@github.com/bencejdanko/bert-tweeteval

# ensure latest
os.chdir('/content/bert-tweeteval')
!cd /content/bert-tweeteval && git pull

Cloning into 'bert-tweeteval'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 69 (delta 32), reused 48 (delta 16), pack-reused 0 (from 0)
Receiving objects: 100% (69/69), 114.43 KiB | 1.66 MiB/s, done.
Resolving deltas: 100% (32/32), done.
Already up to date.

In [3]:
# copy over package
PACKAGE = "src"

import sys
sys.path.append(f"/content/bert-tweeteval/{PACKAGE}")

In [4]:
from download import download_and_split_dataset
from train import train_and_evaluate

import pandas as pd
from datasets import Dataset

from corruption import create_corruption_ablations
from domain_shift import create_shift_ablation_sets
from transformers import Trainer, AutoModelForSequenceClassification, AutoTokenizer

In [5]:
id_labels = {0: "anger", 1: "joy", 2: "optimism", 3: "sadness"}
labels_id = {"anger": 0, "joy": 1, "optimism": 2, "sadness": 3}
candidate_labels = list(id_labels.values())
hypothesis_template = "This tweet expresses {}."

In [6]:
train_df, val_df, test_df = download_and_split_dataset()
print(f"Training set: {len(train_df)}")
print(f"Validation set: {len(val_df)}")
print(f"Testing set: {len(test_df)}")

README.md: 0.00B [00:00, ?B/s]

emotion/train-00000-of-00001.parquet:   0%|          | 0.00/233k [00:00<?, ?B/s]

emotion/test-00000-of-00001.parquet:   0%|          | 0.00/105k [00:00<?, ?B/s]

emotion/validation-00000-of-00001.parque(…):   0%|          | 0.00/28.6k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3257 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1421 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/374 [00:00<?, ? examples/s]

Training set: 3257
Validation set: 374
Testing set: 1421

In [7]:
# create validation split

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
test_ds = Dataset.from_pandas(test_df)

In [8]:
ft_results = {}

In [11]:
import torch
import os
import sys

sys.path.append('.') # Ensure current dir for local imports

from train import evaluate # Updated to a simplified eval if needed or from src
import pandas as pd
from transformers import Trainer, AutoModelForSequenceClassification, AutoTokenizer
from corruption import create_corruption_ablations
from domain_shift import create_shift_ablation_sets

repo_id = "bdanko/bert-tweeteval"
model_names = [f"{repo_id}-distilbert", f"{repo_id}-distilroberta"]
ft_results = {}

for model_name in model_names:
    print(f"\n{'='*50}")
    print(f"Evaluating model: {model_name}")
    print(f"{'='*50}")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name)

    # Dummy trainer for evaluation function
    trainer = Trainer(model=model)

    ft_results[model_name] = {}

    # 1. Standard evaluation
    ft_results[model_name]["standard"] = evaluate(trainer, tokenizer, test_df, model_name, candidate_labels)

    # 2. Corruption Ablations
    print(f"\nRunning corruption ablations for {model_name}...")
    corrupted_dfs = create_corruption_ablations(test_df)
    ft_results[model_name]["corruptions"] = {}
    for name, c_df in corrupted_dfs.items():
        ft_results[model_name]["corruptions"][name] = evaluate(trainer, tokenizer, c_df, f"{model_name}_{name}", candidate_labels)

    # 3. Domain Shift Ablations
    print(f"\nRunning domain shift ablations for {model_name}...")
    shift_dfs = create_shift_ablation_sets(test_df)
    ft_results[model_name]["shifts"] = {}
    for name, s_df in shift_dfs.items():
        ft_results[model_name]["shifts"][name] = evaluate(trainer, tokenizer, s_df, f"{model_name}_{name}", candidate_labels)

==================================================
Evaluating model: bdanko/bert-tweeteval-distilbert
==================================================

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert on provided dataset (size: 1421)...

Running corruption ablations for bdanko/bert-tweeteval-distilbert...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_original on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_corruption_typos on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_corruption_hashtags on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_corruption_emojis on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_corruption_all on provided dataset (size: 1421)...

Running domain shift ablations for bdanko/bert-tweeteval-distilbert...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_full_test on provided dataset (size: 1421)...

Map:   0%|          | 0/614 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_with_mentions on provided dataset (size: 614)...

Map:   0%|          | 0/807 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_no_mentions on provided dataset (size: 807)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_no_links on provided dataset (size: 1421)...

Map:   0%|          | 0/673 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_with_hashtags on provided dataset (size: 673)...

Map:   0%|          | 0/748 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilbert_no_hashtags on provided dataset (size: 748)...

==================================================
Evaluating model: bdanko/bert-tweeteval-distilroberta
==================================================

config.json:   0%|          | 0.00/930 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/359 [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta on provided dataset (size: 1421)...

Running corruption ablations for bdanko/bert-tweeteval-distilroberta...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_original on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_corruption_typos on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_corruption_hashtags on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_corruption_emojis on provided dataset (size: 1421)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_corruption_all on provided dataset (size: 1421)...

Running domain shift ablations for bdanko/bert-tweeteval-distilroberta...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_full_test on provided dataset (size: 1421)...

Map:   0%|          | 0/614 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_with_mentions on provided dataset (size: 614)...

Map:   0%|          | 0/807 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_no_mentions on provided dataset (size: 807)...

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_no_links on provided dataset (size: 1421)...

Map:   0%|          | 0/673 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_with_hashtags on provided dataset (size: 673)...

Map:   0%|          | 0/748 [00:00<?, ? examples/s]

Evaluating bdanko/bert-tweeteval-distilroberta_no_hashtags on provided dataset (size: 748)...

In [12]:
import pandas as pd
from IPython.display import display

print("\nCorruption Ablations")
corr_rows = []
for model in ft_results:
    for c_name, res in ft_results[model]["corruptions"].items():
        corr_rows.append({
            "Model": model.split('/')[-1],
            "Corruption": c_name,
            "Accuracy": res["Accuracy"]
        })
corr_summary = pd.DataFrame(corr_rows).pivot(index="Corruption", columns="Model", values="Accuracy")
display(corr_summary)

print("\nDomain Shift Ablations")
shift_rows = []
for model in ft_results:
    for s_name, res in ft_results[model]["shifts"].items():
        shift_rows.append({
            "Model": model.split('/')[-1],
            "Shift": s_name,
            "Accuracy": res["Accuracy"]
        })
shift_summary = pd.DataFrame(shift_rows).pivot(index="Shift", columns="Model", values="Accuracy")
display(shift_summary)

Corruption Ablations

Model                bert-tweeteval-distilbert  bert-tweeteval-distilroberta
Corruption
corruption_all                        0.778325                      0.776918
corruption_emojis                     0.798030                      0.784659
corruption_hashtags                   0.802956                      0.795215
corruption_typos                      0.779733                      0.769177
original                              0.805771                      0.787474

Domain Shift Ablations

Model          bert-tweeteval-distilbert  bert-tweeteval-distilroberta
Shift
full_test                       0.805771                      0.787474
no_hashtags                     0.790107                      0.795455
no_links                        0.805771                      0.787474
no_mentions                     0.789343                      0.779430
with_hashtags                   0.823180                      0.778603
with_mentions                   0.827362                      0.798046